name: Run Jupyter Notebook

on:
  push:
    branches:
      - main  # Triggers when code is pushed to main

jobs:
  notebook-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install papermill pandas==2.2.2 scikit-learn==1.6.1 numpy==2.0.0

      - name: Execute notebook
        run: |
          papermill Iris_KNN_Classification.ipynb output.ipynb
